require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ComunesController do

  # This should return the minimal set of attributes required to create a valid
  # Comune. As you add validations to Comune, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ComunesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all comunes as @comunes" do
      comune = Comune.create! valid_attributes
      get :index, {}, valid_session
      assigns(:comunes).should eq([comune])
    end
  end

  describe "GET show" do
    it "assigns the requested comune as @comune" do
      comune = Comune.create! valid_attributes
      get :show, {:id => comune.to_param}, valid_session
      assigns(:comune).should eq(comune)
    end
  end

  describe "GET new" do
    it "assigns a new comune as @comune" do
      get :new, {}, valid_session
      assigns(:comune).should be_a_new(Comune)
    end
  end

  describe "GET edit" do
    it "assigns the requested comune as @comune" do
      comune = Comune.create! valid_attributes
      get :edit, {:id => comune.to_param}, valid_session
      assigns(:comune).should eq(comune)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Comune" do
        expect {
          post :create, {:comune => valid_attributes}, valid_session
        }.to change(Comune, :count).by(1)
      end

      it "assigns a newly created comune as @comune" do
        post :create, {:comune => valid_attributes}, valid_session
        assigns(:comune).should be_a(Comune)
        assigns(:comune).should be_persisted
      end

      it "redirects to the created comune" do
        post :create, {:comune => valid_attributes}, valid_session
        response.should redirect_to(Comune.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved comune as @comune" do
        # Trigger the behavior that occurs when invalid params are submitted
        Comune.any_instance.stub(:save).and_return(false)
        post :create, {:comune => { "name" => "invalid value" }}, valid_session
        assigns(:comune).should be_a_new(Comune)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Comune.any_instance.stub(:save).and_return(false)
        post :create, {:comune => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested comune" do
        comune = Comune.create! valid_attributes
        # Assuming there are no other comunes in the database, this
        # specifies that the Comune created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Comune.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => comune.to_param, :comune => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested comune as @comune" do
        comune = Comune.create! valid_attributes
        put :update, {:id => comune.to_param, :comune => valid_attributes}, valid_session
        assigns(:comune).should eq(comune)
      end

      it "redirects to the comune" do
        comune = Comune.create! valid_attributes
        put :update, {:id => comune.to_param, :comune => valid_attributes}, valid_session
        response.should redirect_to(comune)
      end
    end

    describe "with invalid params" do
      it "assigns the comune as @comune" do
        comune = Comune.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Comune.any_instance.stub(:save).and_return(false)
        put :update, {:id => comune.to_param, :comune => { "name" => "invalid value" }}, valid_session
        assigns(:comune).should eq(comune)
      end

      it "re-renders the 'edit' template" do
        comune = Comune.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Comune.any_instance.stub(:save).and_return(false)
        put :update, {:id => comune.to_param, :comune => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested comune" do
      comune = Comune.create! valid_attributes
      expect {
        delete :destroy, {:id => comune.to_param}, valid_session
      }.to change(Comune, :count).by(-1)
    end

    it "redirects to the comunes list" do
      comune = Comune.create! valid_attributes
      delete :destroy, {:id => comune.to_param}, valid_session
      response.should redirect_to(comunes_url)
    end
  end

end
