require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InsuranceProvidersController do

  # This should return the minimal set of attributes required to create a valid
  # InsuranceProvider. As you add validations to InsuranceProvider, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InsuranceProvidersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all insurance_providers as @insurance_providers" do
      insurance_provider = InsuranceProvider.create! valid_attributes
      get :index, {}, valid_session
      assigns(:insurance_providers).should eq([insurance_provider])
    end
  end

  describe "GET show" do
    it "assigns the requested insurance_provider as @insurance_provider" do
      insurance_provider = InsuranceProvider.create! valid_attributes
      get :show, {:id => insurance_provider.to_param}, valid_session
      assigns(:insurance_provider).should eq(insurance_provider)
    end
  end

  describe "GET new" do
    it "assigns a new insurance_provider as @insurance_provider" do
      get :new, {}, valid_session
      assigns(:insurance_provider).should be_a_new(InsuranceProvider)
    end
  end

  describe "GET edit" do
    it "assigns the requested insurance_provider as @insurance_provider" do
      insurance_provider = InsuranceProvider.create! valid_attributes
      get :edit, {:id => insurance_provider.to_param}, valid_session
      assigns(:insurance_provider).should eq(insurance_provider)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new InsuranceProvider" do
        expect {
          post :create, {:insurance_provider => valid_attributes}, valid_session
        }.to change(InsuranceProvider, :count).by(1)
      end

      it "assigns a newly created insurance_provider as @insurance_provider" do
        post :create, {:insurance_provider => valid_attributes}, valid_session
        assigns(:insurance_provider).should be_a(InsuranceProvider)
        assigns(:insurance_provider).should be_persisted
      end

      it "redirects to the created insurance_provider" do
        post :create, {:insurance_provider => valid_attributes}, valid_session
        response.should redirect_to(InsuranceProvider.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved insurance_provider as @insurance_provider" do
        # Trigger the behavior that occurs when invalid params are submitted
        InsuranceProvider.any_instance.stub(:save).and_return(false)
        post :create, {:insurance_provider => { "name" => "invalid value" }}, valid_session
        assigns(:insurance_provider).should be_a_new(InsuranceProvider)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        InsuranceProvider.any_instance.stub(:save).and_return(false)
        post :create, {:insurance_provider => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested insurance_provider" do
        insurance_provider = InsuranceProvider.create! valid_attributes
        # Assuming there are no other insurance_providers in the database, this
        # specifies that the InsuranceProvider created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        InsuranceProvider.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => insurance_provider.to_param, :insurance_provider => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested insurance_provider as @insurance_provider" do
        insurance_provider = InsuranceProvider.create! valid_attributes
        put :update, {:id => insurance_provider.to_param, :insurance_provider => valid_attributes}, valid_session
        assigns(:insurance_provider).should eq(insurance_provider)
      end

      it "redirects to the insurance_provider" do
        insurance_provider = InsuranceProvider.create! valid_attributes
        put :update, {:id => insurance_provider.to_param, :insurance_provider => valid_attributes}, valid_session
        response.should redirect_to(insurance_provider)
      end
    end

    describe "with invalid params" do
      it "assigns the insurance_provider as @insurance_provider" do
        insurance_provider = InsuranceProvider.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InsuranceProvider.any_instance.stub(:save).and_return(false)
        put :update, {:id => insurance_provider.to_param, :insurance_provider => { "name" => "invalid value" }}, valid_session
        assigns(:insurance_provider).should eq(insurance_provider)
      end

      it "re-renders the 'edit' template" do
        insurance_provider = InsuranceProvider.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InsuranceProvider.any_instance.stub(:save).and_return(false)
        put :update, {:id => insurance_provider.to_param, :insurance_provider => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested insurance_provider" do
      insurance_provider = InsuranceProvider.create! valid_attributes
      expect {
        delete :destroy, {:id => insurance_provider.to_param}, valid_session
      }.to change(InsuranceProvider, :count).by(-1)
    end

    it "redirects to the insurance_providers list" do
      insurance_provider = InsuranceProvider.create! valid_attributes
      delete :destroy, {:id => insurance_provider.to_param}, valid_session
      response.should redirect_to(insurance_providers_url)
    end
  end

end
